### ISSUE TITLE
Newsfeed isn't working as expected

### ISSUE THREAD

**Issue by zenkeku** [HugoFara/lwt#100]
**Describe the bug**
Refer to image. I don't have the knowledge to describe further.

NOTE! Only happens if Farsi is set as default language.

**To Reproduce**
Click on "newsfeed"
Also, trying to add new feed results in second screenshot

**Expected behavior**
No scary boxes.

**Screenshots**

![Screenshot 2023-03-14 at 10 21 43 AM](https://user-images.githubusercontent.com/6876494/225031452-e8d9bacf-598e-4d62-95ad-a7d682733b7a.png)
![Screenshot 2023-03-14 at 10 24 45 AM](https://user-images.githubusercontent.com/6876494/225031939-89ed7c65-75d5-4c70-9d63-ce446e0c1172.png)

**Desktop (please complete the following information):**
 - OS: Mac Ventura 13.3
 - Browser Microsoft Edge
 - Version Latest

**Comment by HugoFara** [comment]
Hi!

The implementation of news fees is quite bad (undocumented and unreadable code), so I consider this feature legacy and I don't want to spend time fixing it, sorry. For now I advise not to use it.

That being said, I tried to make the code at least readable, so I pushed a bunch of edits, you can try to use [18edb02](https://github.com/HugoFara/lwt/commit/18edb02c43c466509a47f3139eab32b2f10b9ded), it includes a bug fix that may solve your issue.

**Comment by maanh96** [comment]
Hello, not sure if this fixes your problem but I get the feeds working by changing line #475 (#487 in the latest version) in do_feeds.php from 
`if($currentfeed==0 || strpos($temp, $currentfeed)===false) { `
to 
`if($currentfeed==0 || strpos($temp, $currentfeed)===false || strpos($temp, $currentfeed)==0) {`

**Comment by HugoFara** [comment]
Hi, thanks @maanh96 for your hint! This issue should be fixed now, as well as many others, but the news feed is still quite buggy unfortunately.
