### ISSUE TITLE
Installation on Public Web Server

### ISSUE THREAD

**Issue by OverClockd** [HugoFara/lwt#105]
I installed this on a public web server (LAMP) with Debian base.
I tried a couple of times but as soon as I perform a fresh install (clean database, clean file structure, and NOT using the install.sh (I just rename the connection.inc.php and edit the info)), import a long text of Spanish, when I go to read it, I am not showing any translations. The words are highlighted but clicking them does not produce anything in the side panels, they remain blank.

L1 Language = English
L2 Language = Spanish

I am running on Lubuntu w/ Firefox

I'd imagine it is something I am messing up and this probably isn't the place to post this so my apologies in advance! I wasn't sure where else to seek help.

PM me if you would like a direct link to the installation to which you can visit it and try for yourself.

Thank you!

**Comment by jzohrab** [comment]
Hi @OverClockd, I don't have an answer for LWT, but you could also try my project "Lute", which was based on the ideas in LWT.  The repo is https://github.com/jzohrab/lute.  I use Lute for studying Spanish as well, I run it on my Mac.  It will at least get you started with the idea of LWT, so you can see if you like this method of studying.  When @HugoFara sorts out the issue with LWT you could return to it.  Cheers! Jeff

(@HugoFara - really hope you don't mind me dropping this note here -- thought it over before posting, thought you'd be ok with it. jz)

**Comment by HugoFara** [comment]
I think it's an iframe-related issue here, some website won't allowed to be displayed embedded. You can modify your dictionary url to make it display in iframes.

For instance if you dictionary url is: ``https://example.com/definition/`` you can change it to ``https://example.com/definition/lwt_term?lwt_popup=1``.
