### ISSUE TITLE
New installation is unusable

### ISSUE THREAD

**Issue by HenryWales** [HugoFara/lwt#110]
The bugs I see are huge. They must not show up for most users. It's like javascript being broken on LWT pages.

Drop down to select page : doesn't work at all. 
Clicking on a word to display tooltip, definition and dictionary : do nothing
On the "my texts" page statistics like "total words" of a text are empty
Maybe more

Buttons that are links to an url that do something work

Browser : Firefox 112. no extension active on localhost
Server: XAMPP
PHP version : 8.1
LWT version : 2.8.1
Installation : copy of the unzipped content of lwt-2.8.1 into empty xampp/htdocs/lwt

My XAMPP runned official LWT without problem. I moved official LWT DB and files before installing this fork.

**Comment by HugoFara** [comment]
Hi! I think your JavaScript code associated to LWT is not running at all :smile: Let me explain.

Your browser is using an old version of the code, most likely the one associated with the official LWT. You need to refresh the cache: either hit ``Ctrl+F5``, ``Ctrl+R``, wait until your browser does it b yourself or use another browser in the meantime. Issues should be gone.

Issues like this are not easy to catch on dev side, so I did not include any way of displaying problems, I may should add one for users in the future.

**Comment by HenryWales** [comment]
After deleting website cache, the scripts are working as expected. Thanks for the help.

Some warning in the installation instruction about cache if replacing an old LWT would be good. Easier to do than new code but still helpful.
