### ISSUE TITLE
Depending on the active language's settings, hide the romanization field

### ISSUE THREAD

**Issue by HenryWales** [HugoFara/lwt#119]
This is a minor enhancement request.

When creating or editing a term, the romanization field is always displayed. It is very important for language not using the latin script. Working on a language written with latin script however,

Maybe some people use the romanization field for something else than its original purpose (insert heating spacebar comics), but when it's not used it only takes valuable UI space. If it's just a checkbox in the language settings like "Make each character a word", it would be perfect.

**Comment by HugoFara** [comment]
Great news, I added your suggestions in LWT 2.10.0, have fun!
![image](https://github.com/HugoFara/lwt/assets/72709893/1dfc0e43-698d-4c3e-b3ef-2267a0255f0f)
