### ISSUE TITLE
OS 'DAR' not found for MeCab

### ISSUE THREAD

**Issue by HugoFara** [HugoFara/lwt#135]
when I open a text now, it shows the following...

Fatal Error: Your OS 'DAR' cannot use MeCab with this version of LWT!

Backtrace:

#0 /Applications/MAMP/htdocs/lwt-2.8.1/inc/kernel_utility.php(268): my_die('Your OS 'DAR' c...')
#1 /Applications/MAMP/htdocs/lwt-2.8.1/inc/session_utility.php(4498): get_mecab_path(' -O yomi ')
#2 /Applications/MAMP/htdocs/lwt-2.8.1/do_text_header.php(186): phonetic_reading('\xE8\x8C\xA8\xE5\x9F\x8E\xE7\x9C\x8C\xE3\x81\xAE\xE7\xB4\x8D...', 'ja')
#3 /Applications/MAMP/htdocs/lwt-2.8.1/do_text_header.php(313): browser_tts('\xE8\x8C\xA8\xE5\x9F\x8E\xE7\x9C\x8C\xE3\x81\xAE\xE7\xB4\x8D...', 'Japanese')
#4 /Applications/MAMP/htdocs/lwt-2.8.1/do_text.php(96): do_text_header_content(3, true)
#5 /Applications/MAMP/htdocs/lwt-2.8.1/do_text.php(144): do_text_desktop_content(3)
#6 /Applications/MAMP/htdocs/lwt-2.8.1/do_text.php(150): do_text_page(3)

_Originally posted by @quopquai in https://github.com/HugoFara/lwt/issues/134#issuecomment-1624704329_

@quopquai is using a Mac M2.

**Comment by HugoFara** [comment]
Hmmm, it seems I never tried MeCab with a Mac as I don't own one. I may ask you a small contribution @quopquai :smile: 

First, did you install MeCab? It is not shipped with LWT and needs to be installed separately.

Second, can you open a terminal and tell me if this command works ``command -v mecab`` please? If so, I may add a support for MeCab Mac...

**Comment by quopquai** [comment]
I have no idea if I installed it or not!? I might have!?

...when I type the command, nothing seems to happen...

<img width="682" alt="Screenshot 2023-07-07 at 13 41 38" src="https://github.com/HugoFara/lwt/assets/88017080/46e353b9-6594-4105-9b7b-8d7517920067">

**Comment by HugoFara** [comment]
Okay, so MeCab is not installed. You need to install it first, and the previous command returns the location of the binary. Unfortunately I cannot recommend you a good tutorial as I don't have a Mac, but I already read that you can install it with homebrew.

Once that's done, we can work one an integration of MeCab for Mac!

**Comment by quopquai** [comment]
...ok I think I've done it...

<img width="745" alt="Screenshot 2023-07-07 at 13 57 52" src="https://github.com/HugoFara/lwt/assets/88017080/9ec37b6b-a1f9-4449-9f9a-c0020d98d56e">

**Comment by HugoFara** [comment]
Nice! Let's perform some live surgery on LWT!

Can you go to line 250 of ``kernel_utility.php`` (``/Applications/MAMP/htdocs/lwt-2.8.1/inc/kernel_utility.php(268)``), and do the following substitution?

From
```php
if ($os == 'LIN') {
```
to
```php
if ($os == 'LIN' || $os == 'DAR') {
```

If MeCab works with that, I'm adding the feature!

**Comment by quopquai** [comment]
...I changed it...and saved...

<img width="658" alt="Screenshot 2023-07-07 at 14 12 34" src="https://github.com/HugoFara/lwt/assets/88017080/26077eeb-2581-4e13-a1f8-ee0b13d0f21b">

lwt is giving me this now:

Fatal Error: MeCab not detected! Please install it and add it to your PATH.

Backtrace:

#0 /Applications/MAMP/htdocs/lwt-2.8.1/inc/kernel_utility.php(254): my_die('MeCab not detec...')
#1 /Applications/MAMP/htdocs/lwt-2.8.1/inc/session_utility.php(4498): get_mecab_path(' -O yomi ')
#2 /Applications/MAMP/htdocs/lwt-2.8.1/do_text_header.php(186): phonetic_reading('[7\xE6\x9C\x884\xE6\x97\xA5 16\xE6\x99\x82...', 'ja')
#3 /Applications/MAMP/htdocs/lwt-2.8.1/do_text_header.php(313): browser_tts('[7\xE6\x9C\x884\xE6\x97\xA5 16\xE6\x99\x82...', 'Japanese')
#4 /Applications/MAMP/htdocs/lwt-2.8.1/do_text.php(96): do_text_header_content(1, true)
#5 /Applications/MAMP/htdocs/lwt-2.8.1/do_text.php(144): do_text_desktop_content(1)
#6 /Applications/MAMP/htdocs/lwt-2.8.1/do_text.php(150): do_text_page(1)

**Comment by HugoFara** [comment]
I think you installed MeCab on your computer, but MAMP cannot access its path and cannot find it. I'm not sure about how to solve it :thinking: 

I'm looking online...

**Comment by HugoFara** [comment]
> Please install it and add it to your PATH.

By the way, did you do that?

**Comment by quopquai** [comment]
...no, how do you do that?

**Comment by HugoFara** [comment]
I'm copy/pasting from <https://apple.stackexchange.com/questions/41542/adding-a-new-executable-to-the-path-environment-variable>

In your case, you can add ``usr/local/bin/mecab``, then reload the server. I hope that will work :no_mouth:

**Comment by quopquai** [comment]
I'm sorry for the delay:

Macintosh:~ julisco$ usr/local/bin/mecab
-bash: usr/local/bin/mecab: No such file or directory
Macintosh:~ julisco$ 

I have no idea what is going on?!

**Comment by HugoFara** [comment]
I cannot be sure... I think the best solution for now is to try having a working instance of MeCab, then run LWT, and if it doesn't work you may need to configure MAMP to use the good path (I'm really not sure how MAMP works)...

**Comment by quopquai** [comment]
I found this in my terminal when installing MeCab:

xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

does it mean anything?

**Comment by HugoFara** [comment]
I have no idea what that is, sorry :disappointed:

**Comment by quopquai** [comment]
https://github.com/jzohrab/lute/wiki/Mecab-and-Apache

MAMP (Mac users)
Run the following in terminal to adjust the MAMP Apache server PATH:

printf 'export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"' >> /Applications/MAMP/Library/bin/envvars

**Comment by ProgramComputer** [comment]
@HugoFara 
> printf 'export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"' >> /Applications/MAMP/Library/bin/envvars

Add this in docs and close issue.
