### ISSUE TITLE
Error, syntax error (  index.php ) on line 96

### ISSUE THREAD

**Issue by AxmanaleX** [HugoFara/lwt#139]
Guys i have a problem, i cant use LWT, i've set it up already, i've installed EasyPHP 17.0, i've drag "lwt"  (unzipped) into /C:\Program Files\EasyPHP-Devserver-17\eds-www, i've renamed " connect.php.inc "to "connect.inc" but when i start the server and go to "http://127.0.0.1/lwt" it said:

Parse error: syntax error, unexpected ':', expecting '{' in C:\Program Files\EasyPHP-Devserver-17\eds-www\lwt\index.php on line 96

PD: I am ultra supper dummy at these things and i dont know absolutly nothing about how to use/program code or something like that, i just followed the steps that "https://hugofara.github.io/lwt/docs/info.html#install" said.

![image](https://github.com/HugoFara/lwt/assets/124070334/22590b63-17b4-4abd-bc6a-69762ea6c322)

**Comment by HugoFara** [comment]
Hello, there is 99.99 % chance that your PHP version is below 8.0.

You need your PHP version to be 8.0 at least, see the options [here](https://warehouse.easyphp.org/inventory-devserver#php). Hope that works out! :smile:
