### ISSUE TITLE
Azure TTS and Google Neural2 support for text-to-speech

### ISSUE THREAD

**Issue by nepisodes** [HugoFara/lwt#143]
Support for adding users' own API keys for these two text-to-speech services (or others) would be so great!

**Comment by HugoFara** [comment]
Hi, thanks for your suggestion!

They both seem very popular TTS services, I don't want to implement any service that exists but they seem popular enough so I will have a look about it.

Did you know what needs to be implemented and have you tried to implement it yourself? For now I'm quite busy and will most likely won't be able to work on it before November. If I get a pull request that would be much faster though 😃

**Comment by HugoFara** [comment]
Implemented in #153 and published in LWT 2.10.0!
