### ISSUE TITLE
Some demo newsfeeds are not live

### ISSUE THREAD

**Issue by ProgramComputer** [HugoFara/lwt#148]
The Japanese, Korean, and Chinese Newsfeeds are not live in the demo.

**Comment by HugoFara** [comment]
Thank you for the bug report! I think I'll just remove those feeds since the newsfeed feature is abandoned...

**Comment by HugoFara** [comment]
I removed the feeds "National Geographic News", "Nikkei", "Últimas Notícias - Diário Catarinense", "Hankyoreh" and "The Chairman's Bao". The other feeds seems to be still alive. Cheers!
