### ISSUE TITLE
Why isn't Delete used here?

### ISSUE THREAD

**Issue by ProgramComputer** [HugoFara/lwt#151]
https://github.com/HugoFara/lwt/blob/d8e22588ffeebb67f3623de113e9fa342af3749f/edit_languages.php#L148

There could be an issue for unsupported languages. Create two unsupported languages possible with #150 and delete both or delete two supported languages. The second language can't be deleted due to duplicate key error.

Error message below - 
<img width="823" alt="Screenshot 2023-12-27 163329" src="https://github.com/HugoFara/lwt/assets/22284856/9fa66d9a-eabb-49ae-923e-3f98c486e1dc">

**Comment by HugoFara** [comment]
I can't see any reason, and it creates a bug. A just added the delete instruction and works fine.
