### ISSUE TITLE
Key down not occurring in Test mode

### ISSUE THREAD

**Issue by ProgramComputer** [HugoFara/lwt#159]
https://github.com/HugoFara/lwt/blob/d8e22588ffeebb67f3623de113e9fa342af3749f/src/js/jq_pgm.js#L528
I can key up when solution is not open but not keydown.

**Comment by HugoFara** [comment]
Thank you for signaling this inconsistent behavior. I gave it a though, and I think it's better to always wait for answer before setting score.

**Comment by ProgramComputer** [comment]
@HugoFara The behavior has changed from https://github.com/HugoFara/lwt/blob/6ec40a6714d05b048020c351b33207be4252311a/src/js/jq_pgm.js . Then the space showed the solution and other keys were allowed after space was pressed. The docs aren't clear that some keys aren't available after/before the solution opens.
