### ISSUE TITLE
PHP warning on index.php with Docker install

### ISSUE THREAD

**Issue by PeterHero** [HugoFara/lwt#160]
**Describe the bug**
A docker installed lwt gets php warning on index.php:

**To Reproduce**

0. Start Docker by `docker compose up`
1. Go to 'http://localhost:8010/index.php'
2. See warning `PHP Warning:  file_get_contents(UNLICENSE.md): Failed to open stream: No such file or directory in /var/www/html/inc/session_utility.php on line 5238`

**Expected behavior**
See no warning

**Server (please complete)**
Data 	Value
LWT version 	v002008001
Web Server 	Apache/2.4.38 (Debian)
Server Software 	Apache/2.4.38
Server Location 	localhost:8010
PHP Version 	8.1.20

- LWT version: [e.g. 2.8.0]

**Desktop (if necessary):**

- OS: Arch linux
- Browser firefox
- Version 120

**Additional context**
My lwt is installed with docker.

**Comment by ProgramComputer** [comment]
@HugoFara All .md files are ignored in https://github.com/HugoFara/lwt/blob/403b2b484ea846baa8114ca28478d8c89ca90f4c/.dockerignore#L16  .
Related to docker help #146 .
