### ISSUE TITLE
Test ALL terms inside terms fails with traceback

### ISSUE THREAD

**Issue by txwikinger** [HugoFara/lwt#192]
**Describe the bug**
When using test all terms inside the terms page, an error message and tracback is shown

**To Reproduce**

1. Go to 'terms' inside the Multiaction section
2. Click on  the multi-selection box titled 'All n Terms' -> Test  ALL terms
3. See error

Fatal Error: do_test_test.php called with wrong parameters

Backtrace:

#0 /var/www/html/lwt/inc/session_utility.php(782): my_die('...')
#1 /var/www/html/lwt/inc/session_utility.php(802): do_test_test_get_projection('...', Array)
#2 /var/www/html/lwt/do_test.php(62): do_test_test_from_selection(2, '...')
#3 /var/www/html/lwt/do_test.php(187): get_l2_language_name()
#4 /var/www/html/lwt/do_test.php(260): do_test_desktop_page()
#5 /var/www/html/lwt/do_test.php(277): do_test_page('...')
#6 /var/www/html/lwt/do_test.php(285): try_start_test('...')
Signal this issue on [GitHub](https://github.com/HugoFara/lwt/issues/new/choose) or [Discord](https://discord.gg/xrkRZR2jtt).

**Expected behavior**
I can to the testing pages for the terms

**Screenshots**

**Server (please complete)**
You can copy/paste data from http://[.. your LWT installation]/server_data.php.

<?php

/**
 * \file
 * \brief Useful software data.
 * 
 * Call: server_data.php
 * 
 * PHP version 8.1.1
 * 
 * @category User_Interface
 * @package  Lwt
 * @author   HugoFara <hugo.farajallah@protonmail.com>
 * @license  Unlicense <http://unlicense.org/>
 * @link     https://hugofara.github.io/lwt/docs/php/files/index.html
 * @since    2.7.0
 */

namespace Lwt\Interface\Server\Data;

require_once 'inc/session_utility.php';

/**
 * Return a lot of different server state variables.
 *
 * @return (false|float|string)[] {"db_prefix": string, "db_size": float, "server_soft": string[], 
 * "apache": string, "php": string, "mysql": string} 
 * Table prefix, database size, server software, apache version, PHP version, MySQL 
 * version
 *
 * @global string $tbpref Database table prefix
 * @global string $dbname Database name
 *
 * @psalm-return array{db_name: string, db_prefix: string, db_size: float, server_soft: string, apache: string, php: false|string, mysql: string}
 */
function get_server_data_table(): array 
{
    global $tbpref, $dbname;
    $dbaccess_format = convert_string_to_sqlsyntax($dbname);
    $data_table = array();
    $data_table["db_name"] = $dbname;
    $data_table["db_prefix"] = $tbpref;
    $temp_size = get_first_value(
        "SELECT ROUND(SUM(data_length+index_length)/1024/1024, 1) AS value 
        FROM information_schema.TABLES 
        WHERE table_schema = $dbaccess_format 
        AND table_name IN (
            '{$tbpref}archivedtexts', '{$tbpref}archtexttags', 
            '{$tbpref}feedlinks', '{$tbpref}languages',
            '{$tbpref}newsfeeds', '{$tbpref}sentences', '{$tbpref}settings', 
            '{$tbpref}tags', '{$tbpref}tags2', 
            '{$tbpref}textitems2', '{$tbpref}texts', '{$tbpref}texttags', 
            '{$tbpref}words', '{$tbpref}wordtags'
        )"
    );
    if ($temp_size === null) { 
        $data_table["db_size"] = 0.0; 
    } else {
        $data_table["db_size"] = floatval($temp_size);
    }

    $data_table["server_soft"] = $_SERVER['SERVER_SOFTWARE'];
    $data_table["apache"] = "Apache/?";
    if (str_starts_with($data_table["server_soft"], "Apache/")) {
        $temp_soft = explode(' ', $data_table["server_soft"]);
        $data_table["apache"] = $temp_soft[0];
    }
    $data_table["php"] = phpversion();
    $data_table["mysql"] = (string)get_first_value("SELECT VERSION() AS value");
    return $data_table;
}

/**
 * Display the main content for the page.
 * 
 * @return void
 */
function display_content(): void
{
    $data = get_server_data_table();

    pagestart("Server Data", true);
    ?>
<h2>Server</h2>
<table>
    <thead>
        <tr>
            <th>Data</th>
            <th>Value</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>LWT version</td>
            <td><?php echo get_version_number(); ?></td>
        </tr>
        <tr>
            <td>
                <a href="https://en.wikipedia.org/wiki/Web_server" target="_blank">
                    Web Server
                </a>
            </td>
            <td><i><?php echo $data["server_soft"]; ?></i></td>
        </tr>
        <tr>
            <td>Server Software</td>
            <td>
                <a href="https://en.wikipedia.org/wiki/Apache_HTTP_Server" 
                target="_blank">
                    <?php echo $data["apache"]; ?>
                </a>
            </td>
        </tr>
        <tr>
            <td>Server Location</td>
            <td><i><?php echo $_SERVER['HTTP_HOST']; ?></i></td>
        </tr>
        <tr>
            <td>
                <a href="https://en.wikipedia.org/wiki/PHP" target="_blank">
                    PHP
                </a> Version
            </td>
            <td><?php echo $data["php"]; ?></td>
        </tr>
    </tbody>
</table>
<h2>Database</h2>
<table>
    <thead>
        <tr>
            <th>Data</th>
            <th>Value</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                <a href="https://en.wikipedia.org/wiki/Database" target="_blank">
                    Database
                </a> name</td>
            <td><i><?php echo $data["db_name"]; ?></i></td>
        </tr>
        <tr>
            <td>Database prefix (surrounded by "")</td>
            <td>"<?php echo $data["db_prefix"]; ?>"</td>
        </tr>
        <tr>
            <td>Database Size</td>
            <td><?php echo $data["db_size"]; ?> MB</td>
        </tr>
        <tr>
            <td>
                <a href="https://en.wikipedia.org/wiki/MySQL" target="_blank">
                    MySQL
                </a> Version
            </td>
            <td><?php echo $data["mysql"]; ?></td>
        </tr>
    </tbody>
</table>
<h2>Client API</h2>
<table>
    <thead>
        <tr>
            <th>Data</th>
            <th>Value</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                <a href="https://en.wikipedia.org/wiki/REST">
                    REST API
                </a> Version
            </td>
            <td id="rest-api-version"></td>
        </tr>
        <tr>
            <td>
                <a href="https://en.wikipedia.org/wiki/REST">
                    REST API
                </a> Release date
            </td>
            <td id="rest-api-release-date"></td>
        </tr>
    </tbody>
</table>
<script type="text/javascript">
    function handle_api_version_answer(data) {
        if ("error" in data) {
            $("#rest-api-version").text(
                "Error while getting data from the REST API!" +
                "\nMessage: " + data.error
            );
            $("#rest-api-release-date").empty();
        } else {
            $("#rest-api-version").text(data.version);
            $("#rest-api-release-date").text(data.release_date);
        }
    }

    $.getJSON(
        "api.php/v1/version",
        {},
        handle_api_version_answer
    );
</script>
    <?php
    pageend();
}

display_content();

- LWT version: [e.g. 2.8.0]
Use docker install (master branch ) on Feb 18 2024

**Desktop (if necessary):**

- OS: [e.g. iOS] ChromeOS
- Browser [e.g. chrome, safari] Chrome
- Version [e.g. 22] 119

**Smartphone (if necessary):**

**Additional context**

**Comment by HugoFara** [comment]
Hi @txwikinger ! Thank you for the bug report, I fixed it, it was one line of code acting up (missing 's' character at [inc/session_utility#L747](https://github.com/HugoFara/lwt/blob/e733ada19bec8347c5826a58e00d2be29f4c37e8/inc/session_utility.php#L747)).

Have a good day!
