### ISSUE TITLE
Cannot edit Improved Annotated Text

### ISSUE THREAD

**Issue by Nick0w7** [HugoFara/lwt#193]
Cannot edit the annotated text when I click on edit in the Improved annotated text tab . 
I noticed this was necessary in order for the translations to show up when I click on "Translations" on the main reading tab.
- LWT version: LWT-Master

- OS: Android 
- Browser Chrome
- Version 12
![image](https://github.com/HugoFara/lwt/assets/164795039/ce52b050-9fc5-403c-bb9b-672181608f78)
![PXL_20240324_194634419](https://github.com/HugoFara/lwt/assets/164795039/147cb19b-2dde-4458-b3ff-6ce0e61dbc3d)

**Comment by HugoFara** [comment]
Hi, thanks for the bug report. I found the solution in line 344 of ``inc/ajax_impr_edit_text.php`` (https://github.com/HugoFara/lwt/blob/832adb2b399113ca05604d2a8aeddee5f3d18882/inc/ajax_edit_impr_text.php#L344), ``$wid`` (null) should have been replaced by ``$str_wid`` (string || null).

I fixed on dev, will publish on master soon.

**Comment by Nick0w7** [comment]
Hi,
Thanks for the fix! 
By the way, do you know when we will be able to select multiple words to make an expression (like creating "word-expression")
Thank you for the improvements.

**Comment by HugoFara** [comment]
Mutli-word creation is possible to do it with a mouse (click and maintain on a word until the rest of the sentence is lit up), but unfortunately it is not available with touch devices such as your tablet. I included details on #142, and I cannot say if or when it will be implement as it requires rewriting the interaction system.

Have a good day!
