### ISSUE TITLE
Get error when add text 

### ISSUE THREAD

**Issue by nghiaphamtm** [HugoFara/lwt#25]
When I tried to import text into my website but I got an error.

```
Fatal Error in SQL Query: LOAD DATA LOCAL INFILE '/tmp/tmpti.txt' INTO TABLE temptextitems FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n' (@w,@c) set TiSeID = @b, TiCount = (@d:=@d+CHAR_LENGTH(@c))+1-CHAR_LENGTH(@c), TiOrder = if(@c like "%\r",case when (@c:=REPLACE(@c,"\r","")) is NULL then NULL when (@b:=@b+1) is NULL then NULL when @d:= @e is NULL then NULL else @a:=@a+1 end, @a:=@a+1), TiText = @c,TiWordCount=@w

Error Code & Message: [1148] The used command is not allowed with this MariaDB version

```
![image](https://user-images.githubusercontent.com/102361929/160115572-05c21682-c3dd-4cca-bc61-e92c7608fc01.png)

I don't know how to fix this, My SQL version is ****10.3.28-MariaDB-cll-lve** and PHP version is 8.0.3**

Can you tell me how to fix this? Thank you very much.

**Comment by HugoFara** [comment]
Hello,

It seems like a simple permission issue. Could you specify what OS you are using?

Make sure to follow the [installation guide](https://github.com/HugoFara/lwt/blob/master/docs/install.md), it should be okay once everything is correctly set up.

**Comment by nghiaphamtm** [comment]
I tried to set up it in a shared hosting service but it seemed like I need a dedicated server for that. 

So I try to set it up again on my computer which is Windows 10. But it also has some errors.

When I first defined first language it showed some errors:

![image](https://user-images.githubusercontent.com/102361929/160269761-c71cd386-2315-460f-83ba-a59603f25ce6.png)

And when I tried to change the language, it also gives me a bunch of errors. Here are some of them.

`Notice: Undefined variable: _SESSION in C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\lwt-master\lwt-master\save_setting_redirect.php on line 16`
`Notice: Undefined variable: _SESSION in C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\lwt-master\lwt-master\save_setting_redirect.php on line 17`
`Warning: Cannot modify header information - headers already sent by (output started at C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\lwt-master\lwt-master\save_setting_redirect.php:29) in C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\lwt-master\lwt-master\save_setting_redirect.php on line 54`

I can add text into it but when I insert audio it again gives me local_infile problem

![image](https://user-images.githubusercontent.com/102361929/160270040-0cb1cacd-b2a5-49cd-b571-859bae3a283e.png)

**I'm using EasyPHP 
OS:                            Windows 10
Server Software:	Apache/2.4.25
PHP Version:	        7.4.19
MySQL Version:	5.7.17**

Thank you for your time.

**Comment by HugoFara** [comment]
Hi!

Let's break down the different problems you have here.

## LOAD DATA LOCAL INFILE
Could you try the solutions exposed in #20 ? I copy/pasted the relevant part:
```
1. Check your server authorizations. You might have a setting saying something "allow local files imports" or "file_uploads".
2. Check your database users authorizations. Could you run MySQL, execute SHOW GRANTS; and paste the result?
3. Run MySQL and check that SHOW VARIABLES LIKE ‘%local_infile%’; is "ON"?
```

## Undefined variable: _SESSION
This issue seem to be quite rare, so it may take a few time for me to reproduce it. Normally, a session should start automatically, as it is not the case for you, I may add a patch to check if everything runs correctly.

Coud you add ``session_start();`` at line 15 of ``save_setting_redirect.php``? It won't really solve the issue, but another error should occur, telling us why the server refuses to start the session.

**Comment by nghiaphamtm** [comment]
> Coud you add `session_start();` at line 15 of `save_setting_redirect.php`? It won't really solve the issue, but another error should occur, telling us why the server refuses to start the session. A better way to fix it is to set `session.autostart` to "true" (`1` or `On`) in your `php.ini` file.

I added `session_start();` at line 15 of `save_setting_redirect.php` as you said and it worked perfectly normal.

But I can't solve LOAD DATA LOCAL INFILE problem. I change it into **ON** but it didn't work at all.

And can you tell me how to fix `Uninitialized string offset` notice as I mentioned above

**Comment by HugoFara** [comment]
Hi, the good news is that no new problem was created by adding ``session_start()``, so it only means you have to change your server configuration to automatically start the session, the ``session.autostart`` (in ``php.ini``) should do the trick.

For the LOAD DATA part, it is quite a common issue in PHP. As it is related to *your* server configuration, I can't do much, so try to find relevant topics on the net. Maybe changing ``mysqli.allow_local_infile = On`` in your ``php.ini`` should solve this. I'm sorry I can't do more, I did not write this part of the code, and I may change it is it causes many issues.

For the ``Unitialized string offset``, that comes from a bad type comparison (something like ``"" > 0``). It is mostly a warning stemming from another problem. I don't think there is a useful way to solve it. What's more, I did not write the ``edit_languages.php`` file and had no time yet to refactor it, so that's why the code is quite bad for now. 

Hope it helps you

**Comment by nghiaphamtm** [comment]
Finally, I can set LWT up on my computer, it runs very smoothly except when I click the `I know all button` it returned an error.
```
Fatal Error in SQL Query: SELECT DISTINCT Ti2Text, Ti2TextLC FROM (textitems2 LEFT JOIN words ON (Ti2TextLC = WoTextLC) AND (Ti2LgID = WoLgID) ) WHERE Ti2IsNotWord = 0 AND WoID IS NULL AND Ti2WordCount = 1 AND Ti2TxID = 1 ORDER BY Ti2Order

Error Code & Message: [1054] Unknown column 'Ti2TextLC' in 'field list'
```


If anyone runs into LOCAL INFILE problem as I did. You should uncomment it in server configuration rather than trying to find the file and uncomment it.

**Comment by HugoFara** [comment]
I'm glad to know that we finally solved your problem. As many should struggle with the same issue as yours, I hope to develop a more user-friendly alternative.

I created a new issue for your last problem, but it should get fixed in the next release.
