### ISSUE TITLE
Parse error: syntax error, unexpected ':', expecting '{' in C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\lwt\inc\session_utility.php on line 87

### ISSUE THREAD

**Issue by Mitsuki42** [HugoFara/lwt#30]
thank you for the great work. 
could you please look into this error? this is what i see as soon as i finish all the installation process.

Parse error: syntax error, unexpected ':', expecting '{' in C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\lwt\inc\session_utility.php on line 87

![image](https://user-images.githubusercontent.com/104381322/165138251-d05f00de-68c4-4c04-bc3a-8c464fda71c2.png)

**Comment by HugoFara** [comment]
Hello!

It seems that you are using an outdated version of PHP (below PHP 7.1). Try updating it to PHP 7.4.

If you want more help, could you give me the following information:
* Your PHP version
* The LWT version you are using

**Comment by HugoFara** [comment]
Well, it seems that EasyPHP 17.0 uses PHP 7.1.3 by default, which reached [end-of-life in 2019](https://www.php.net/supported-versions.php). Hopefully, EasyPHP enables you to update your PHP version, please see the [inventory devserver page](https://warehouse.easyphp.org/inventory-devserver#php). For LWT 1.3.0, I recommend you to use PHP 7.4.

I hope it solves your issue!
