### ISSUE TITLE
Broken UI, can't import or parse long texts on 2.4.0

### ISSUE THREAD

**Issue by rc-ops** [HugoFara/lwt#31]
Hi!
I've been testing (or trying to) test the new version as soon as I saw the [2.4.0 release](https://github.com/HugoFara/lwt/releases/tag/2.4.0) and I got the time. Well, here are my findings.

**First problem: UI**
- There are a lot of UI buttons that aren't functional, in special the ones from the dropdown. 
- Also, you can see that after clicking on the checkbox to select the text and parse it, delete and et cetera, the dropdown to the right side of _Marked text_ doesn't became enabled, as you can see at the image below

>![1](https://user-images.githubusercontent.com/72221896/170493854-16adb09f-f4a0-4712-bbde-2dff835ec340.jpg)

**Second problem: text import**
- Well, here I am again, trying to parse my 日本語 sub :). You said at #23  that you got the parse working, but unfortunately I couldn't test it, because:
1. If I try to import a long text (doesn't matter if I paste or select a txt file), when I select _NEXT STEP: Check the texts_ I get an error message and as you can see, it doesn't seem to process the text, it returns _Length: 0 Bytes_, and two of the buttons here don't work (_Cancel_ and _Go Back_), only the _Create 1 text_, which returns us to the UI problem.
> Notice: Undefined index: TextTags in C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\lwt\long_text_import.php on line 30
Warning: Invalid argument supplied for foreach() in C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\lwt\long_text_import.php on line 67

![2](https://user-images.githubusercontent.com/72221896/170498031-47256f8d-8dd3-4f29-97d6-9583e0b2ef7b.jpg)

1.1 After selecting _Create 1 text_, since it's null, I get

> Fatal Error in SQL Query: insert into texts (TxLgID, TxTitle, TxText, TxAnnotatedText, TxAudioURI, TxSourceURI) values( 1, 'Mondaiji 2', NULL, '', NULL, NULL)
Error Code & Message: [1048] Column 'TxText' cannot be null
```
Backtrace:

#0  do_mysqli_query(insert into texts (TxLgID, TxTitle, TxText, TxAnnotatedText, TxAudioURI, TxSourceURI) values( 1, 'Mondaiji 2', NULL, '', NULL, NULL)) called at [C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\lwt\inc\database_connect.php:60]
#1  runsql(insert into texts (TxLgID, TxTitle, TxText, TxAnnotatedText, TxAudioURI, TxSourceURI) values( 1, 'Mondaiji 2', NULL, '', NULL, NULL), ) called at [C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\lwt\long_text_import.php:160]
```

- The only way I can import a text is if paste it in _New Text_, it can't be through _Long Text_. Note that here the _Check_ button more or less... works? However it graphically represents the line breaks and the line numbers. Is that intended?
> ![3](https://user-images.githubusercontent.com/72221896/170500681-c431423a-a6b5-44e0-9c33-a3968379d47f.jpg)
- I can also see that it returns a _word list_ and _non-word list_ which is cool and would that mean MeCab is working... ?
- But since it doesn't parse, nor can I select it to parse manually, it doesn't save any new terms.

**Third problem: text reading**
- When reading imported text, if I select _I KNOW ALL_, a message appears asking if I'm sure, even though I am, it doesn't save any terms.
- If I click on any words, the sidebar to create a new term doesn't appear.
- The buttons marked in red don't work.
> ![4](https://user-images.githubusercontent.com/72221896/170502367-b67d963b-8983-4eac-b420-5a63f21102cf.jpg)

**Forth problem: the parsing per se**
- So before submitting the issue, I realised that I could go to _My Languages_ section and parse from there. It returns some numbers, but I'm not really sure if it's doing anything because If I go the My Texts, there's still no words or any info whatsoever
- This section still returns a notice
`Notice: Undefined variable: 0 in C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\lwt\edit_languages.php on line 725`
> ![5](https://user-images.githubusercontent.com/72221896/170506690-3dc4d2b2-6c46-45b9-a485-23f33be0360e.jpg)
- After clicking to parse, still no info about the text.
> ![6](https://user-images.githubusercontent.com/72221896/170507025-e2e1336d-2ebc-4bed-b313-df748b901ec8.jpg)

**Desktop (please complete the following information):**
 - Same setup as last time, except this time Chromium has another version
 - OS: Windows 11 21H2 and Windows 10 20H2
- Browser: Chromium 101.0.4951.64
- EasyPHPDevserver-17 PHP 7.1.3

Phew! That took a while to write. Sorry for the long text. In fact it isn't that long, the images make it so. Does the images throughout the text help or should they go to a separate section at the end of the post?
I also couldn't make the docker version work, but I'll reference that in another issue.

**Comment by rc-ops** [comment]
Also forgot to mention that I can't delete the imported text through the UI, so I had to truncate the text table to do so.

**Comment by HugoFara** [comment]
Hi, so sorry to know that such annoying bugs subsisted :/

Would you mind creating issues for each one of them, I'd like to keep things organized for future developments. You can copy/paste the text of course.

Except for your UI problem, I am unable to reproduce some of your bugs (I will tell you which one in separated issue), one thing I may advise you is to update to PHP 7.4. PHP 7.1 [reached end-of-life in 2018](https://www.php.net/supported-versions.php), so it can be a source of issues.

Otherwise I should most of the bugs are easy to solve, maybe by the end of this week they will be over.

For the images, you can either post them in the message or after it it is not a problem. 

Regarding the Docker version, which one did you use? Never hesitate to open a new issue if you think something is broken :wink: 

それじゃ、またね！

**Comment by rc-ops** [comment]
> Would you mind creating issues for each one of them, I'd like to keep things organized for future developments. You can copy/paste the text of course.

Sure. They are #32, #33, #34 and #35.

> Except for your UI problem, I am unable to reproduce some of your bugs (I will tell you which one in separated issue), one thing I may advise you is to update to PHP 7.4. PHP 7.1 [reached end-of-life in 2018](https://www.php.net/supported-versions.php), so it can be a source of issues.

Yeah, I thought so. I can't exactly remember why, but I guess I one of my reasons for using it was because of incompatibility with the original LWT. When I get the time I'll try updating it and see if some of the bugs get solved just by the update. I'll let you know in one of the created issues.
