### ISSUE TITLE
Can't import texts

### ISSUE THREAD

**Issue by rc-ops** [HugoFara/lwt#33]
Extracted from #31 

1. If I try to import a long text (doesn't matter if I paste or select a txt file), when I select _NEXT STEP: Check the texts_ I get an error message and as you can see, it doesn't seem to process the text, it returns _Length: 0 Bytes_, and two of the buttons here don't work (_Cancel_ and _Go Back_), only the _Create 1 text_, which returns us to the UI problem.
> Notice: Undefined index: TextTags in C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\lwt\long_text_import.php on line 30
Warning: Invalid argument supplied for foreach() in C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\lwt\long_text_import.php on line 67

![2](https://user-images.githubusercontent.com/72221896/170498031-47256f8d-8dd3-4f29-97d6-9583e0b2ef7b.jpg)

1.1 After selecting _Create 1 text_, since it's null, I get

> Fatal Error in SQL Query: insert into texts (TxLgID, TxTitle, TxText, TxAnnotatedText, TxAudioURI, TxSourceURI) values( 1, 'Mondaiji 2', NULL, '', NULL, NULL)
Error Code & Message: [1048] Column 'TxText' cannot be null
```
Backtrace:

#0  do_mysqli_query(insert into texts (TxLgID, TxTitle, TxText, TxAnnotatedText, TxAudioURI, TxSourceURI) values( 1, 'Mondaiji 2', NULL, '', NULL, NULL)) called at [C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\lwt\inc\database_connect.php:60]
#1  runsql(insert into texts (TxLgID, TxTitle, TxText, TxAnnotatedText, TxAudioURI, TxSourceURI) values( 1, 'Mondaiji 2', NULL, '', NULL, NULL), ) called at [C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\lwt\long_text_import.php:160]
```

- The only way I can import a text is if paste it in _New Text_, it can't be through _Long Text_. Note that here the _Check_ button more or less... works? However it graphically represents the line breaks and the line numbers. Is that intended?
> ![3](https://user-images.githubusercontent.com/72221896/170500681-c431423a-a6b5-44e0-9c33-a3968379d47f.jpg)
- I can also see that it returns a _word list_ and _non-word list_ which is cool and would that mean MeCab is working... ?
- But since it doesn't parse, nor can I select it to parse manually, it doesn't save any new terms.

**Desktop (please complete the following information):**
 - Same setup as last time, except this time Chromium has another version
 - OS: Windows 11 21H2 and Windows 10 20H2
- Browser: Chromium 101.0.4951.64
- EasyPHPDevserver-17 PHP 7.1.3

**Comment by HugoFara** [comment]
Hello!

I have been trying to solve the long_text_import this issue today, without much success for Japanese. For other languages, I managed to fix problems introduced in 2.4.0, but for Japanese I'm still facing a formatting issue.

That being said, the main problem is that the code is a mess, so it's always difficult to sort out who does what...

For the normal text import, the data displayed when clicking *Check* are what was needed, so it it means MeCab is working fine. I'm not sure why you are still unable to save the text.


I hope to release the bug fix version on Monday, I will give you more information there.
