### ISSUE TITLE
Unable to create/ignore a term longer than the parsed by MeCab

### ISSUE THREAD

**Issue by rc-ops** [HugoFara/lwt#34]
Extracted from #31 

- When reading imported text, if I select _I KNOW ALL_, a message appears asking if I'm sure, even though I am, it doesn't save any terms.
- If I click on any words, the sidebar to create a new term doesn't appear.
- The buttons marked in red don't work.
> ![4](https://user-images.githubusercontent.com/72221896/170502367-b67d963b-8983-4eac-b420-5a63f21102cf.jpg)

**Desktop (please complete the following information):**
 - Same setup as last time, except this time Chromium has another version
 - OS: Windows 11 21H2 and Windows 10 20H2
- Browser: Chromium 101.0.4951.64
- EasyPHPDevserver-17 PHP 7.1.3

**Comment by HugoFara** [comment]
After some tests, I think that the problem may be a bit different. Clicking "I KNOW ALL" should work, but to see it you have to manually reload the page. This is a UX problem as things may be better, but hopefully not something really annoying.

For the sidebar and the "Read in browser" button, I think that your JavaScript is disabled for local files. A lot of functionalities won't work then so try enabling it in your browser settings (Settings → Privacy and Security → Site Settings → JavaScript). Hope it solves your problem ;)

**Comment by rc-ops** [comment]
Hi!
So after removing everything related to LWT, truncating the database (which I did before upgrading) and restarting EasyPHP in the process, I checked my browser console log, turns out it wasn't a javascript problem, which didn't make sense since I had been developing some JS stuff this week. Apparently ublock was blocking some 3rd party website, in this case jisho.org and google's tracking triggered by it. That's strange, because I hadn't problems with it before.
Apparently it also closes #32 
Sorry. I should've tested it with a clean browser! :P

**Comment by rc-ops** [comment]
Ok... I'm still having problems saving/ignoring some terms

```
New Term: さかまきいざよい
Fatal Error in SQL Query: SELECT WoID, WoTextLC FROM words WHERE WoLgID in(@m) AND WoWordCount = 0 into outfile 'C:\\Users\\USER\\AppData\\Local\\Temp\\db_440E.tmp'

Error Code & Message: [1290] The MySQL server is running with the --secure-file-priv option so it cannot execute this statement

Backtrace:

#0  do_mysqli_query(SELECT WoID, WoTextLC FROM words 
            WHERE WoLgID in(@m) AND WoWordCount = 0 
            into outfile 'C:\\Users\\USER\\AppData\\Local\\Temp\\db_440E.tmp') called at [C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\lwt\inc\database_connect.php:585]
#1  set_word_count() called at [C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\lwt\edit_mword.php:53]
```
![chrome_sYfUdQWnyy](https://user-images.githubusercontent.com/72221896/171153598-9b9a29e1-ba30-4344-b4d8-11fd52be5ee7.jpg)

- I can sometimes trigger this error by doing:
1. Go to some other LWT page
2. Open the text to read
3. Click and drag from the beginning to the end of the word, like mentioned in #21 
4. Select word status _Ign_ and Save the term

- Apparently it gets trigged by a specific sentence, in this case the one containing さかまきいざよい. The sentence is:

> （逆廻十六夜(さかまき いざよい)）
> 何か面白いことねえかなあ

**Comment by HugoFara** [comment]
I was able to fix your issue, saving the file in the SQL folder instead of the server's "temp" directory, so that the "secure-file-priv" flag should no longer be necessary. For the markup referenced in #21, it is a broader issue, still being investigated, any help would be appreciated!

I'm closing this issue as the problem specific to Japanese is fixed, but I'm aware that things still need a patch...
