### ISSUE TITLE
Inconsistent word highlighting when same word appears in different texts.

### ISSUE THREAD

**Issue by jzohrab** [HugoFara/lwt#47]
**Description**

(let me know if this is user error!)

**Text 1**

I created a text and marked some words as known, some as learning.  (I also clicked "I know all" at some point, which gave some bugs, so perhaps my db is somehow inconsistent and this is not a real issue):

![image](https://user-images.githubusercontent.com/1637133/198901952-5793ab05-4834-47c0-b5dd-a7a8c9990aa8.png)

**Text 2**

I then copied part of that text into a new text.  Note that all of the words show up as known (except for those which are learning):

![image](https://user-images.githubusercontent.com/1637133/198902006-038b3e31-9dde-4b96-ab2a-3bc8d57aca40.png)

**Expected behaviour**

Text 2 should have shown the same highlights as Text 1 ... but again, there may be some problem with the database that I'm not sure about.

cheers! jz

**Comment by jzohrab** [comment]
It is very possible that this is due to some sort of inconsistent data in the db.  I just created two short identical texts, and the highlighting is consistent for both of them.  @HugoFara Let me know if you want some data dumped from the database for the inconsistent ones. Cheers, z

**Comment by HugoFara** [comment]
>  I can try to reproduce if you'd like

Well, I can't reproduce your bug, so it would help if you could do so :)

There is a high probability that the "All Know All" button is guilty here. If so, it got fixed by #49 .

**Comment by jzohrab** [comment]
Yes, I think this one can be closed, feels like a dup now.
