### ISSUE TITLE
"set all to known" doesn't seem to stick, and then creates problems when trying to create terms

### ISSUE THREAD

**Issue by jzohrab** [HugoFara/lwt#48]
**1. New text:** Create a new short text, all words unknown:

![image](https://user-images.githubusercontent.com/1637133/198905745-8ec09519-44e7-4796-9682-df84c7cc306b.png)

**2. click:** Click "set all to known"

![image](https://user-images.githubusercontent.com/1637133/198905758-0fe1545b-a296-492a-b17f-50109de07aa0.png)

**3. Refresh page:** refresh the page, and all words again appear as blue, with status = "unknown" in the popup.

![image](https://user-images.githubusercontent.com/1637133/198905781-0f40d8c7-04df-4ed4-b224-27f11fe25fc9.png)

**4. Try to learn one of the words:** click a word, and try to mark it as "learn", get error:

```
Fatal Error in SQL Query: INSERT INTO words ( WoLgID, WoText, WoTextLC, WoStatus, WoWordCount, WoStatusChanged, WoTodayScore, WoTomorrowScore, WoRandom ) values( 1, 'negro', 'negro', 99, 1, NOW(), ...[SNIP]..., RAND() )

Error Code & Message: [1062] Duplicate entry 'negro-1' for key 'WoTextLCLgID'
```

Currently running on 'dev' branch:

```
commit 956ffce285ea7452384079d8f79cf73b40a3b86e (HEAD -> dev, origin/dev)
Author: HugoFara <hugo.farajallah@protonmail.com>
Date:   Sun Oct 30 16:20:39 2022 +0900

    Fixed #46: I know all crashing on duplicate words.
```

**Comment by jzohrab** [comment]
Testing with a word with all caps, thinking it had something to do with the lower-case vs original word, same result:

**initial text**

![image](https://user-images.githubusercontent.com/1637133/198925501-9dfed960-585d-49e3-8953-43050567e4d4.png)

**click "set all to known"**

![image](https://user-images.githubusercontent.com/1637133/198925610-672cf4b8-13e8-4e07-ad35-c79279f23245.png)

**refresh page**

![image](https://user-images.githubusercontent.com/1637133/198925670-bbb3e2bc-c162-43c1-928b-607ac341a887.png)

Actually, with the new dev branch, even when I mark a word as "learn", it still shows up on the reading screen as blue, and on the popup as known, when it shows up in the right frame as "learn":

![image](https://user-images.githubusercontent.com/1637133/198926421-2d3abde6-01d9-4e59-bea1-77b3b0809a22.png)

**Comment by jzohrab** [comment]
I don't know the data model or the code well, but was curious so started to look.  I imagine that the problem has something to do with how `textitems2` is loaded.

Using the "PERRO coche" text from the above comment:

```
mysql> select txid, txlgid, txtext from texts where txid = 3;
+------+--------+--------------+
| txid | txlgid | txtext       |
+------+--------+--------------+
|    3 |      1 | PERRO coche. |
+------+--------+--------------+
```

the `words` records were created:

```
mysql> select woid, wolgid, wotext, wotextlc, wostatus from words where wotext in ('PERRO', 'coche');
+------+--------+--------+----------+----------+
| woid | wolgid | wotext | wotextlc | wostatus |
+------+--------+--------+----------+----------+
|  571 |      1 | PERRO  | perro    |       99 |
|  572 |      1 | coche  | coche    |        4 |
+------+--------+--------+----------+----------+
```

but in `textitems2` the tx2woid is 0:

```
mysql> select * from textitems2 where ti2txid = 3;
+---------+---------+---------+---------+----------+--------------+---------+----------------+
| Ti2WoID | Ti2LgID | Ti2TxID | Ti2SeID | Ti2Order | Ti2WordCount | Ti2Text | Ti2Translation |
+---------+---------+---------+---------+----------+--------------+---------+----------------+
|       0 |       1 |       3 |     168 |        1 |            1 | PERRO   |                |
|       0 |       1 |       3 |     168 |        2 |            0 |         |                |
|       0 |       1 |       3 |     168 |        3 |            1 | coche   |                |
|       0 |       1 |       3 |     168 |        4 |            0 | .       |                |
+---------+---------+---------+---------+----------+--------------+---------+----------------+
```

and Ti2WoID is used as the join field in `do_text_text.php` function `function main_word_loop($textid, $showAll): void`:

```
function main_word_loop($textid, $showAll): void
{
    global $tbpref;
    
    $sql = 
    "SELECT
     CASE WHEN `Ti2WordCount`>0 THEN Ti2WordCount ELSE 1 END AS Code,
     CASE WHEN CHAR_LENGTH(Ti2Text)>0 THEN Ti2Text ELSE `WoText` END AS TiText,
...[SNIP]...
     FROM {$tbpref}textitems2 LEFT JOIN {$tbpref}words ON Ti2WoID = WoID
     WHERE Ti2TxID = $textid
     ORDER BY Ti2Order asc, Ti2WordCount desc";
```

**Comment by jzohrab** [comment]
Final comment on this bug: I think that after processing all the words in `all_words_wellknown.php`, something like the following query in `uploads_words.php` should be done to associate the records in `textitems2` to the new `words` records:

```
    runsql(
        "UPDATE {$tbpref}words 
        JOIN {$tbpref}textitems2 
        ON WoWordCount=1 AND Ti2WoID=0 AND lower(Ti2Text)=WoTextLC AND Ti2LgID = WoLgID 
        SET Ti2WoID=WoID", 
        ''
    );
```

Then the `main_word_loop` query would be fine.

**Comment by HugoFara** [comment]
Thanks for the pull request! I'll close this issue when merging the dev branch to master if no new problem appears.
