### ISSUE TITLE
Google translate fails for whole sentence, but succeeds for a phrase with the exact same terms.

### ISSUE THREAD

**Issue by jzohrab** [HugoFara/lwt#58]
For me, google translate sentence always fails the first time the window opens, eg.:

![image](https://user-images.githubusercontent.com/1637133/199862296-643c18c0-5ce0-4385-8d7f-391a35255b21.png)

I have to click the "retry" button, at which point the translation works.

Interestingly, when I create a multi-word phrase that is the same as the sentence (excluding the punctuation), the translation succeeds:

![image](https://user-images.githubusercontent.com/1637133/199862453-a817ef89-d965-4c0c-938e-ae90ff36fee2.png)

(I've tried it with phrases that have punctuation, and the translation still succeeds.

This is on a Mac, Spanish language.  There's something different about how the translation is called for a phrase, vs a full sentence.

**Comment by jzohrab** [comment]
URL for first click for "sentence translate" (fails first time):
```
https://translate.google.com/?ie=UTF-8&sl=es&tl=en&text=Todav%C3%ADa+recuerdo,+aquel+amanecer.
```

Url used in js for "translate term" (works):
```
http://translate.google.com/?ie=UTF-8&sl=es&tl=en&text=Todav%C3%ADa+recuerdo%2C+aquel+amanecer
```

It feels likely that the thing that is causing the sentence translation to fail is that the punctuation (comma and sentence period) are not being properly escaped.

**Comment by jzohrab** [comment]
(note: I don't really follow why this is so complicated, so I'll need @HugoFara to guide this :-P )

Backtracking.  translateSentence2 does some magic with the URL it's given, and ultimately calls the js function `owin()` with this string:

```
trans.php?x=2&i=http%3A//translate.google.com/%3Fie%3DUTF-8%26sl%3Des%26tl%3Den%26text%3D%23%23%23&t=Todavía recuerdo, aquel amanecer.
```

trans.php then looks at **magic parameter** `x=2` and then does a header to set the location to `{http://translate.google.com/?ie=UTF-8&sl=es&tl=en&text=Todav%C3%ADa+recuerdo%2C+aquel+amanecer.}` ... it's possible that Google Translate doesn't like header redirects with parameters due to XSS issues, since when I open a window in my browser with that URL, everything works just fine.

... wow this code is very hard to grok.

Now, it seems to me that we can vastly simplify all of this, but I must be missing something.  When we call `translateSentence2`, we have the following params:

```
url => http://translate.google.com/?ie=UTF-8&sl=es&tl=en&text=###
text => "Todavía recuerdo, aquel {amanecer}."
```

@HugoFara , why can't we just use those params and create the URL that we need to call, right in Javascript?  This would skip all the calls back and forth to PHP for makeTheDictURL and trans.php and other things.

**Comment by HugoFara** [comment]
> why can't we just use those params and create the URL that we need to call, right in Javascript?

In fact we can, so we did :smile: 

I have no been able to reproduce your issue though, so I took your PR as a healthier basis for a bug fix. Normally, it should work, but as I cannot be 100% sure, tell me if I have to reopen this issue!
