### ISSUE TITLE
Suggestion: add "canonical term" to words to show word "parents"

### ISSUE THREAD

**Issue by jzohrab** [HugoFara/lwt#68]
## Rough description

I feel that a central idea that Lingq and LWT lack is the idea of "canonical term" for a word.  Many words are just declensions of other words, and so it doesn't make sense to have to define the same idea several times.  For example, if a text says "Yo tengo un gato" and "tú tienes un gato", "tengo" and "tienes" are both forms of "tener".

It would be great if words could be linked with canonical terms, and the canonical term info (translation, tags) were automatically "inherited" during display and filtering.

## UX idea

(pardon the crappy picture)

![image](https://user-images.githubusercontent.com/1637133/200398352-464228e6-540a-4c5f-9303-ea198c13f602.png)

Essentially, there would be a drop-down box, likely autofill, that would just show the existing `words` entries.  If left blank, the word wouldn't have a canonical form.  If a non-existing word was entered as the canonical form, a new "enter word" form would appear, just like the existing one.  If an existing word was chosen, it would be used as the canonical form.

## Implementation

**Pre-requisite: No matter what, this implementation requires database changes, and so something like #54 should be implemented.**

We could just add a new "word_parent" table: `id, parentWoID, childWoID`.  I think this is better than changing the `words` table, b/c it will allow for import of existing backups that people might have.

etc etc. :-P

**Comment by HugoFara** [comment]
Hi Jeff! What you are looking for is the integration of a [lemma](https://en.wikipedia.org/wiki/Lemma_(morphology)) system. I think the easiest way to do it is to use a better dictionary API, as currently LWT is agnostic in term of dictionary used, it makes it very versatile but prevents advanced functions. 

Actually, it's a thing I would like to integrate, so I'm open to suggestions. If you want running examples, some tools as https://www.vocabtracker.com/ already use lemmata.

**Comment by jzohrab** [comment]
Hola Hugo!  Actually, I *wasn't* thinking of a lemma system, but it's really very similar. :-)

I was simply considering a way for me to define a "parent term", so I could add the definition just to the parent, and then create a link to the "child term" I'd encountered in the text.  I also wasn't looking for LWT to find or to make that parent term automatically for me, or to help me when looking it up.

But then again, I'm using thefreedictionary (https://es.thefreedictionary.com/###) for my Spanish, and it automatically lemmatizes things (eg if I say "hablé" it takes me to "hablar", which is super).  Perhaps other languages don't have such a friendly dictionary available, in which case, yes, a lemmatizer would be helpful -- and that is probably what you were suggesting with your comment.

(I've used vocabtracker very briefly but vastly prefer LWT's approach.)

**Comment by HugoFara** [comment]
Oh, okay, so your approach is a bit more manual than a lemmatizer. I'm not sure yet how to implement it because users usually have hundreds of lemmata, but it can be a bit more easy on dev side since the dictionary and languages systems are all so different.

I will probably focus on this enhancement much later though, since I have many others things to fix :smile:
