### ISSUE TITLE
Multi-word terms occasionally don't highlight

### ISSUE THREAD

**Issue by jzohrab** [HugoFara/lwt#70]
This is quite odd -- in some places, mwords highlight, and in others, not.  This persists after page refresh.  For example:

![image](https://user-images.githubusercontent.com/1637133/200626305-2464d470-77a2-450d-9830-b252e8d72b42.png)
...
![image](https://user-images.githubusercontent.com/1637133/200626415-c8c18879-adc6-4af7-ab66-dba31d2d1f0d.png)

Both of the circled terms are defined in the db:

```
mysql> select woid, wolgid, wotext, wotextlc, wowordcount from words where wotext like '%importancia%' or wotext like '%con el tiempo%';
+------+--------+-------------------------+-------------------------+-------------+
| woid | wolgid | wotext                  | wotextlc                | wowordcount |
+------+--------+-------------------------+-------------------------+-------------+
| 5023 |      1 | quitándole importancia  | quitándole importancia  |           2 |
| 5030 |      1 | Con el tiempo           | con el tiempo           |           3 |
+------+--------+-------------------------+-------------------------+-------------+
2 rows in set (0.01 sec)
```

If I click and drag on "quitándole importancia", the term actually shows up in the edit window, so the code can find it.

Not sure what other info to attach to this issue :-)

**Comment by HugoFara** [comment]
Hi!

I think I stumbled across the cause while working on another issue. Here is what happen:
1. In 2.2.2, I removed some code SQL by mistake (typo)
2. Code is unreadable so there was no easy way to figure out the issue.

In a nutshell, I changed those four lines (https://github.com/HugoFara/lwt/blob/8d662cc16f6ed3506add23f302d59c5ce4d64ff3/inc/database_connect.php#L1261-L1264)
```php
        $set_wo_sql .= "WHEN (@a$i := @a".($i-1) . ") IS NULL THEN NULL ";
        $set_wo_sql_2 .= "WHEN (@a$i := @a".($i-2) .") IS NULL THEN NULL ";
        $del_wo_sql .= "WHEN (@a$i := @a0) IS NULL THEN NULL ";
        $init_var .= "@a$i=0,";
```

I removed the string concatenation operator, ``.=``, replacing it by a simple assignment.

As a side not, this is fixed, but this part of the code is largely mysterious and badly coded, so issues may remain
