### ISSUE TITLE
Ukrainian voice issue

### ISSUE THREAD

**Issue by asdrubalivan** [HugoFara/lwt#85]
**Describe the bug**
Wrong Ukrainian voice when using text aloud

**To Reproduce**
I have the following configuration for Ukrainian

![image](https://user-images.githubusercontent.com/1117046/210278675-69343004-0c4a-4b97-bbdc-8257181054e4.png)

**Expected behavior**

It should read in Ukrainian. Right now I'm using google TTS which seems to work

**Screenshots**

**Desktop (please complete the following information):**
- OS: Linux
- Browser: Chrome

**Additional context**
It reads the Cyrillic alphabet with an English like pronunciation. I notice that the ` uk` code for Ukrainian is used. 

Glad to help to solve this issue.

**Comment by asdrubalivan** [comment]
Note: I see that Ukrainian is not supported by the Speech Synthesis API, so I'm closing this for now

**Comment by HugoFara** [comment]
Hi, thanks for reaching out! LWT text-to-speech (TTS) uses your browser's TTS capabilities, so another browser may solve the issue, there is not much I can do here....

**Comment by asdrubalivan** [comment]
I found a workaround using [Readaloud App as a chrome extension](https://readaloud.app/) which uses Google Translate voices and it's pretty accurate. I think this could be added to the docs.

**Comment by HugoFara** [comment]
Hi! I just added your link to the documentation ([postinstall.md#enhanced-text-to-speech](https://github.com/HugoFara/lwt/blob/master/docs/postinstall.md#enhanced-text-to-speech)), thanks for the hint!
