### ISSUE TITLE
"Save button" doesn't appear ( Reading mode, Term panel )

### ISSUE THREAD

**Issue by makeProjectGreatAgain** [HugoFara/lwt#87]
**Describe the bug**
"Save button" doesn't appear ( Reading mode, Term panel )
Look at the screen below

**To Reproduce**
latest master branch ( d549d5a781c954332d7a0771e9f6c512a2a4f604 commit for now )
```
docker compose up -d
```
Go to Texts
Click Reading icon on any text
On Reading screen click on any new (blue) word.
If you try to edit term you'll not be able to save it.
![image](https://user-images.githubusercontent.com/24358142/218837877-c78f8089-2348-4218-80dc-061319a2109b.png)

**Desktop (please complete the following information):**
 - OS: docker 
 - Browser: Chrome, Chromium, Firefox ( all latest version )

**Comment by HugoFara** [comment]
It's not a known bug, could you attach a stack trace (error log in ``/var/log/apache2/error.log``)?

The issue may come from your registered dictionaries, you can try changing their values.

**Comment by makeProjectGreatAgain** [comment]
> It's not a known bug, could you attach a stack trace (error log in ``/var/log/apache2/error.log``)?

Ok, I'll post it a few hours later.
What else should I add?
Maybe Language Settings?

**Comment by HugoFara** [comment]
Your dictionary URL, another user signaled the same issue and we got it fixed by changing the URL.

**Comment by makeProjectGreatAgain** [comment]
> Your dictionary URL, another user signaled the same issue and we got it fixed by changing the URL.

`docker logs lwt`
```
172.21.0.1 - - [18/Feb/2023:17:31:41 +0000] "GET /icn/speaker-volume.png HTTP/1.1" 200 828 "http://localhost:8010/do_text.php?start=10"
[Sat Feb 18 17:31:41.463599 2023] [php:warn] [pid 33] [client 172.21.0.1:37922] PHP Warning:  file_get_contents(UNLICENSE.md): Failed to open stream: No such file or directory in /var/www/html/inc/session_utility.php on line 4932, referer: http://localhost:8010/do_text.php?start=10
[Sat Feb 18 17:31:41.541730 2023] [php:error] [pid 33] [client 172.21.0.1:37922] PHP Fatal error:  Uncaught ValueError: mb_convert_encoding(): Argument #2 ($to_encoding) must be a valid encoding, "#&op=transla" given in /var/www/html/inc/session_utility.php:2695\nStack trace:\n#0 /var/www/html/inc/session_utility.php(2695): mb_convert_encoding()\n#1 /var/www/html/inc/session_utility.php(2733): createTheDictLink()\n#2 /var/www/html/edit_word.php(364): createDictLinksInEditWin()\n#3 {main}\n  thrown in /var/www/html/inc/session_utility.php on line 2695, referer: http://localhost:8010/do_text.php?start=10
172.21.0.1 - - [18/Feb/2023:17:31:41 +0000] "GET /edit_word.php?tid=10&ord=21&wid= HTTP/1.1" 200 2197 "http://localhost:8010/do_text.php?start=10"
```

Dictionary 1 URI: 	`https://translate.google.com/?sl=en&tl=fr&text=####&op=translate`
Sentence Translator URI:  `https://dictionary.cambridge.org/dictionary/english-french/####`

**Comment by HugoFara** [comment]
You incidentally triggered an abandoned feature :open_mouth: 

Replace the four ``#`` by one ``lwt_term`` should solve everything. You can also simply remove "#" as only three "#" should be present, but it will be officially deprecated in version 2.7.0.

In the past, you could specify an encoding writing something like ``###encoding###``, which is why your issue appears.
