### ISSUE TITLE
the installer doesn't work

### ISSUE THREAD

**Issue by loveAnkisomuch** [HugoFara/lwt#88]
![image](https://user-images.githubusercontent.com/23467449/218979996-efa00b3b-8a99-4d8c-acac-236bc773fc9c.png)

Thanks for everyone's help to successfully install LWT2! Thank you!

**Comment by HugoFara** [comment]
Hi! The latest release (2.6.0) has a known bug (view #78), you can download LWT from the master branch (click <https://github.com/HugoFara/lwt/archive/refs/heads/master.zip>), since I fixed it!
