### ISSUE TITLE
The first line of text will be added few spaces once re-edit

### ISSUE THREAD

**Issue by 99MengXin** [HugoFara/lwt#92]
**Describe the bug**
The first line of text will be added few spaces once re-edit.

**To Reproduce**
1. Go to any English text
2. Click on `Edit Text`
3. See error in `Text` column

**Expected behavior**
No space shall be added.

**Screenshots**
<img width="658" alt="截圖 2023-02-16 08 38 04" src="https://user-images.githubusercontent.com/51739513/219228849-2c103127-634a-45de-a789-97009d196ced.png">
fig. 1 Create a new text and click `Save and Open`

-----

<img width="410" alt="截圖 2023-02-16 08 44 31" src="https://user-images.githubusercontent.com/51739513/219228889-7594045d-cdf7-4c5c-987b-98ad3d1186c9.png">
fig. 2 Click `Edit Text` in reading mode

-----

<img width="668" alt="截圖 2023-02-16 08 38 16" src="https://user-images.githubusercontent.com/51739513/219228917-40a8c139-e779-4c22-abd5-0b4bcd53ec24.png">
fig. 3 The first line of text is added few spaces

-----

**Desktop (please complete the following information):**
 - OS: MacOS
 - Safari 16.2
 - Firefox 109.0 
 - Brave 1.48.164

**Smartphone (please complete the following information):**
 - iPhone 8
 - iOS8.1 14.8
 - Safari
 - 14

**Additional context**
This function works well in original LWT.

**Comment by HugoFara** [comment]
Hi, thank you for your issue! I noticed this behavior a long time ago, but it does not cause trouble, so I will investigate it when I will have more time! Feel free to send pull requests!
