### ISSUE TITLE
Using the "look up new words" button, next to the "TODO" causes duplicate database entries

### ISSUE THREAD

**Issue by zenkeku** [HugoFara/lwt#97]
**Describe the bug**

When using this button, the side panel opens up with the definitions. Upon filling it out and clicking the "save" button will submit the appropriate terms into the database, however it isn't reflected in the text. Blue words remain blue words. However, if you click on one, it will load up with the definition that you set. If you try to set the word to "known" or something else, it will throw a SQL error talking about duplicates. The problem can be solved if you click "set all to known" and wait a moment for the text to load.

**To Reproduce**
Refer to above

**Expected behavior**

**Screenshots**

![Screenshot 2023-03-13 at 10 59 51 AM](https://user-images.githubusercontent.com/6876494/224741097-4112a793-552c-4c1c-afb8-31dfe8aaa545.png)

In the above screenshot, all words have an entry, but the blue words still appear. As shown below:

![Screenshot 2023-03-13 at 11 01 43 AM](https://user-images.githubusercontent.com/6876494/224741375-ff8ffb79-696e-43d5-b1e5-4b6898c80479.png)

**Desktop (please complete the following information):**
 - OS: Mac Ventura 13.3
 - Browser Microsoft Edge
 - Version 110.0.1587.69

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by HugoFara** [comment]
Hello!

I'm not sure what was causing it, I think I ran into your a time ago, but now I can no longer reproduce it: everything works fine. Does the issue persists for you with LWT 2.8.0?
